---
title: "Midterm Notes"
subtitle: "Datasci 306"
description: "Midterm Thursday 10/9 during lecture"
format: html
execute:
    warning: false
    message: false
---

```{r}
#library(tidyverse)
suppressPackageStartupMessages(suppressWarnings(library(tidyverse)))
library(dplyr)
library(ggplot2)
```

## Lecture 1: 8-26

```{r}
heights <- read_csv("https://ds306.org/data/survey1.csv")
glimpse(heights)
```

#### Vectors

```{r}
c(1,2,3)
```
```{r}
1:10
```
```{r}
c(1,2,3)[3]
```

#### Operations on Dataframes

```{r}
#help(glimpse)
glimpse(heights)
```
```{r}
#help(summary)
summary(heights)
```
```{r}
#df$colName
heights$`What is your height? (use whichever units you prefer)`
```

###### Renaming Columns

```{r}
#og colnames
colnames(heights)
#Rename Columns
colnames(heights) <- c("timestamp", "sex", "height")
glimpse(heights)
```

```{r}
ncol(heights)
nrow(heights)
```

```{r}
mean(c(1,2,3))
```

```{r}
#Will return 96.6379 - not under same unit (cm or in), 
#too high or too low
mean(heights$height)
```

```{r}
#Hist looks wierd b/c the diff in units
hist(heights$height)
```

```{r}
#Reassign so can type faster
h <- heights$height
```

```{r}
#return a vector of bools
h < 200
```

```{r}
#Removes heights where h < 200 is false
not_big <- h < 200
h[not_big]
```
```{r}
length(h)
length(h[not_big])
```
```{r}
hist(h[not_big])
```

```{r}
h[h < 10]
```

```{r}
length(h[h < 10])
```

```{r}
h_kept <- h[(h >= 50) & (h <= 200)]
```

```{r}
hist(h_kept)
```

```{r}
h_cm1 <- h_kept[h_kept < 100] * 2.54
h_cm2 <- h_kept[h_kept >= 100]

h_cm <- c(h_cm1, h_cm2)
```
```{r}
h_cm
```

```{r}
hist(h_cm)
```
#### Histogram Breaks
```{r}
hist(h_cm, breaks = c(100))
hist(h_cm, breaks = c(10))
```

### Categorial Variables

```{r}
heights$sex
```
```{r}
table(heights$sex)
```
```{r}
# prop table
prop.table(table(heights$sex))
```
```{r}
s <- heights$sex

h[s == "Female"]
```
```{r}
#dplyer
df <- filter(heights, height >= 50, height <= 200)
#if height < 100; multiply by 2.54, otherwise leave it alone
#Put it in new col called scaled_height
df2 <- mutate(df, scaled_height = ifelse(height < 100, 2.54 * height, height))
```
```{r}
hist(df2$scaled_height)
```
```{r}
group_by(df2, sex)
```
```{r}
# Mean height of df2 groups by sex
# Conditional Mean
summarize(group_by(df2, sex), mean(scaled_height))
```

### ggplot
```{r}
#ggplot
ggplot(df2) + geom_histogram(aes(x=scaled_height, fill=sex))
```
```{r}
#Distributions by sex
ggplot(df2) + geom_histogram(aes(x=scaled_height)) + facet_grid(~ sex)
```


## Lecture 2: 8-28

